### ISSUE TITLE
Resizing MPV Window to certain size causes GPU usage to spike

### ISSUE THREAD

**Issue by G4RYWitha4** [bloc97/Anime4K#110]
When streaming a video from youtube via youtube-dl (or any local video file), GPU usage will spike to much higher usage, i.e. 
a window resolution of 2290x1350 will result in ~8% usage according to radeontop on an RX 570, but a window resolution of  2350x1390 will result in ~26% or higher. it can go as high as 55% depending on the stream that im watching. 

I ran`mpv (my URL)` in terminal normally, along with any combination of Anime4K shaders via `--glsl-shaders="(shader 1 location):(shader2 location")` etc

example used:

`mpv https://www.youtube.com/watch?v=5yx6BWlEVcY --deband --contrast=2 --saturation=2 hwdec=0 --glsl-shaders="~~/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl:~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl:~~/shaders/Anime4K_Deblur_DoG.glsl"`

'Anime4K_Upscale_CNN_L_x2_Denoise.glsl' causes the largest difference in GPU usage by far when using the larger window res. but behavior is present in any combination of shaders. other settings such as deband or saturation have no bearing on the outcome.

AFAIK, this only occurs when using the shaders.

 - OS: Pop-OS 20.10
 - GPU Radeon RX 570
 - Media player - MPV 0.32

Screenshots:
![size1](https://user-images.githubusercontent.com/76635563/103162206-a9654000-47e5-11eb-8f74-67b9ab64e56f.png)
![size2](https://user-images.githubusercontent.com/76635563/103162207-ac603080-47e5-11eb-84ae-f34026a1c315.png)

**Comment by Jules-A** [comment]
This is not a bug, the upscaling simply doesn't apply when content isn't 1.2x or less the of the player window size. Check out the discussion in https://github.com/bloc97/Anime4K/issues/109  if you want a better explanation of why. Long story short it's because of this line in the shader files: 

>//!WHEN OUTPUT.w NATIVE.w / 1.200 > OUTPUT.h NATIVE.h / 1.200 > *  

You can edit 1.200 to a lower value, say 1.0 if you want it to activate on 1080p content while playing in a 1080p res or more.


That said, I don't know why 1.2 was chosen and it seems to cause quite a bit of confusion... I think it really should just always apply tbh, it should be up to the user if they want to use those shaders or not and maybe another shader file be created to dynamically scale to resolution.

**Comment by hooke007** [comment]
The usage (8%) was too low when you use the CNN module. It seems it didn't work at all and you may forget

![Snipaste_2020-12-27_16-16-47-tuya](https://user-images.githubusercontent.com/41094733/103166722-c6d6f000-485f-11eb-9b3e-b7aa92e84a4c.jpg)
 to check the stats.

**Comment by G4RYWitha4** [comment]
> This is not a bug, the upscaling simply doesn't apply when content isn't 1.2x or less the of the player window size. Check out the discussion in #109 if you want a better explanation of why. 

> The usage (8%) was too low when you use the CNN module. It seems it didn't work at all and you may forget to check the stats.

That makes more sense, thank you. I guess i underestimated the workload needed, and in hindsight it seemed strange that utilization at the smaller window size wasnt any higher than normal.
