### ISSUE TITLE
Restore shader before or after downscaling?

### ISSUE THREAD

**Issue by wolfdaddyh** [bloc97/Anime4K#132]
Hi, I really love Anime4k shaders and I have one small question: in mode A + A, you put the second restore shader after upscaling while in the other two modes, the second restore shader is put after downscaling x4, I’m wondering will it be better if I put the shader after upscaling and before downscaling in mode B + B?

**Comment by bloc97** [comment]
The downscaling order only matters for ratios that are not x2 or x4. I swapped the order for A+A because it can oversharpen 720p->4K upscales, but B+B usually does not oversharpen and putting the restore after downscaling is faster...

One workaround if speed is important would be to use A+B with the second restore after downscale.
