### ISSUE TITLE
Where can I get the SYNLA_Plus_1024.npy file?

### ISSUE THREAD

**Issue by maheshn22** [bloc97/Anime4K#148]
I am trying to retrain the model, however, I am not able to get the SYNLA_Plus_1024.npy file. I tried downloading the original images from the Synla dataset, but I don't know exactly how to convert the images into the .npy file, so as to successfully create a dataset from that file. 
Can anyone please guide me as to **How do I create the input dataset .npy file?** 
Thanks in advance!

**Comment by bloc97** [comment]
The. npy files are found in the downloads, they are zipped as a .tar archive. https://github.com/bloc97/SYNLA-Plus/releases/tag/v1.0

However note that the SYNLA dataset is used to benchmarking, testing and prototyping models, as it fits in memory and allows faster training and accurate testing. A real dataset of anime + art images is the used to train the final model.

Using SYNLA only might yield poor results on large and overparameterized models.

Real datasets have a lot of variance and the same network trained with the same dataset might give different results if trained a second time just because the real dataset might have been shuffled differently. Using SYNLA just prevents training variance caused by random dataset drift.

**Comment by bloc97** [comment]
Oops, I forgot that the .tar archives contained png files and I didn't include the script to generate the .npy files, sorry for the confusion.

You can use this python script to generate the .npy datasets. You need python 3.x, PIL and numpy. You can modify dataset_folder and np_file if needed. Also be careful, you will need at least triple the size of the dataset as memory to account for decompression, concatenation and saving. There might be more memory-efficient methods out there but they might be more complex...

```py
from PIL import Image
import numpy as np
import os

dataset_folder = "/hdd/sda/SYNLA_Plus_1024/"
np_file = "/hdd/sda/SYNLA_Plus_1024.npy"
np.save(np_file, np.array([np.array(Image.open(dataset_folder + d)) for d in os.listdir(dataset_folder)]))
```

**Comment by maheshn22** [comment]
Ohh I see! Thank you very much for your help :)
