### ISSUE TITLE
java version seems to only upscale images

### ISSUE THREAD

**Issue by FunkyQChicken** [bloc97/Anime4K#20]
Using the build gotten from the ["How to Use"](https://github.com/bloc97/Anime4K/blob/master/Java_Instructions.md) page the program seems to only upscale images.

using the following commands on a given test image,
`java -jar Anime4K.jar test.png out_1.png 2 0.6 0`
`java -jar Anime4K.jar test.png out_2.png 2 1 1`
yields no visual difference between `out_1.png` or `out_2.png`, and running 
`diff out_1.png out_2.png` 
shows that they are the same file.

They were up scaled though.

I tried other images and numbers too, but this example I think gives a concise presentation of my problem and uses almost the same numbers that were on the download page (i had to change the scale)

Looking at the code in the Main file it seems that while actions are run with the 'kernel' variable, it never interacts with the 'img' variable before it is resaved, though I don't have much faith in my assessment of the problem's origin as I don't understand most of the code.

sorry if I've made some simple mistake, I tried to make sure that it wasn't the case but it easily could be.

 - OS: Manjaro Linux
-  Java Version: java-12-openjdk
-  Jar Source: [here](https://github.com/bloc97/Anime4K/releases/download/0.9/Anime4K_Java.zip)

**Comment by k4yt3x** [comment]
I do believe that Anime4K's Java implementation only upscales images. Note that a video is a series of frames + sound and subtitle tracks, where a4k only does the frame upscaling portion.

I have integrated the current Anime4K solution into my waifu2x video upscaling framework and it works well. Feel free to take a look. This tool should help you to actually upscale videos.
https://github.com/k4yt3x/video2x

**Comment by k4yt3x** [comment]
(previous comment deleted as I read the question wrong)

**Comment by bloc97** [comment]
I just tested those two commands, and they produce different files for me.  
For the code, the kernel does interact with the img variable as it passes the RGB array of img by reference to kernel, and the kernel does direct operations on that array on the GPU. After the compute operations it copies the GPU memory back to the system memory.  

This is odd, it might be caused by incompatible Aparapi binaries from the official release. (It was compiled on Windows with OpenCL 2.0)  

If you can try to compile the maven project yourself and see if the problem persists.  
If you need help feel free to comment here.

**Comment by FunkyQChicken** [comment]
By building the project myself using maven and retrying the same commands i get the expected results of differing files that look obviously different. To make sure I double checked using the old jar and it was still just up scaling images. I'm not entirely sure what is going on with the download. Thank you for your help!
