### ISSUE TITLE
Run through ffmpeg (or similar tool)

### ISSUE THREAD

**Issue by BeeeQueue** [bloc97/Anime4K#29]
I've been googling around but haven't been able to find anything useful about running the shader on a video file and saving the output.

**Comment by BeeeQueue** [comment]
Nevermind, I just found https://github.com/k4yt3x/video2x

**Comment by bloc97** [comment]
I'm not familiar with FFMPEG scripting. We also didn't think of a good use scenario for that. Is there any particular reason you need to re-encode a video with this algorithm?
This was intended to be used as a on-line algorithm that can be toggled off at will, since we believe re-encoding a video using this is not ideal.
