### ISSUE TITLE
Reduce oversharpening of edges

### ISSUE THREAD

**Issue by bloc97** [bloc97/Anime4K#3]
Possibly create a second variant for those who find the aliased edges distracting.
The aliasing is noticeable at display densities of under 150 pixels per inch when viewed at typical distances.

Example of oversharpened edges:
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/11.png)

**Comment by THofstee** [comment]
Have you considered running an FXAA shaders over the resulting image?

**Comment by treefroog** [comment]
Yes this would be very nice as I think there is way too much aliasing right now. Other than that I think this is great. Also if you are targeting mpv it would be nice to include a image comparison with FSRCNNX somewhere since that is the primary high quality filter I have seen people using with it. 

Thanks for your work!

**Comment by bloc97** [comment]
Reduced aliasing in Anime4K v1.0 Release Candidate


![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/0_RC.png)
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/1_RC.png)
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/2_RC.png)
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/3_RC.png)
