### ISSUE TITLE
web cannot run

### ISSUE THREAD

**Issue by lephuhung** [bloc97/Anime4K#31]
chrome cannot run with error on console

`Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.
    at createTexture (file:///E:/Download/Anime4K-master/Anime4K-master/web/main.js:56:12)
    at Scaler.inputImage (file:///E:/Download/Anime4K-master/Anime4K-master/web/main.js:487:21)
    at Image.inputImg.onload (file:///E:/Download/Anime4K-master/Anime4K-master/web/main.js:693:16)
createTexture @ main.js:56
Scaler.inputImage @ main.js:487
inputImg.onload @ main.js:693
load (async)
onLoad @ main.js:689
onload @ index.html:11`

**Comment by stefnotch** [comment]
@lephuhung That's a limitation of some web browsers caused by directly opening the `.html` file. You would need a web-server to get around this limitation.

@bloc97 
I think it'd be great if you could set up [GitHub pages](https://pages.github.com/) for this. Setting up GitHub pages just takes a bunch of clicks and ensures that a web demo is always available.

1. Click on the [Settings tab](https://github.com/bloc97/Anime4K/settings) and scroll down to the GitHub Pages section. Then select the master branch source and click on the Save.
2. Add an `index.html` to the root which just redirects you to the other `index.html`
```html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="refresh" content="1;url=web">
        <title>Page Redirection</title>
    </head>
    <body>
        If you are not redirected automatically, <a href="web">click here</a>
    </body>
</html>
```
3. [https://bloc97.github.io/Anime4K](https://bloc97.github.io/Anime4K) should be up

**Comment by lephuhung** [comment]
> @lephuhung That's a limitation of some web browsers caused by directly opening the `.html` file. You would need a web-server to get around this limitation.
> 
> @bloc97
> I think it'd be great if you could set up [GitHub pages](https://pages.github.com/) for this. Setting up GitHub pages just takes a bunch of clicks and ensures that a web demo is always available.
> 
> 1. Click on the [Settings tab](https://github.com/bloc97/Anime4K/settings) and scroll down to the GitHub Pages section. Then select the master branch source and click on the Save.
> 2. Add an `index.html` to the root which just redirects you to the other `index.html`
> 
> ```
> <!DOCTYPE HTML>
> <html lang="en-US">
>     <head>
>         <meta charset="UTF-8">
>         <meta http-equiv="refresh" content="1;url=web">
>         <title>Page Redirection</title>
>     </head>
>     <body>
>         If you are not redirected automatically, <a href="web">click here</a>
>     </body>
> </html>
> ```
> 
> 1. https://bloc97.github.io/Anime4K should be up after a few minutes

many thank to you, i dowloaded xampp and run anime4k perfecterly
