### ISSUE TITLE
Noob here, Can someone giude me to run this? 

### ISSUE THREAD

**Issue by pranavburnwal** [bloc97/Anime4K#5]
Hi,

Noob here so please avoid my ignorance. I am not well versed with the field but would like to convert &/or view Anime. Even to 1080p of old once from 480p will be awesome!

I own a 2017 macPro with Raedon 560.

Thanks!

**Comment by MystesofEternity** [comment]
Since you are using a Mac and I'm unsuare if mac has mpv, your best bet is this
https://github.com/bloc97/Anime4K/blob/master/Java_Instructions.md

You need to ensure java is installed

You can get the files of this software here: https://github.com/bloc97/Anime4K/releases
Releases can be accessed by clicking the part indicating the number of releases, use CTRL + F in https://github.com/bloc97/Anime4K to find it

Making just about anything work in Github takes patience and heart so I hope you understand I can't just spoon feed you everything. Feel free to ask questions as you go through the process of making this work.

If you find out that Mac has mpv player then these set of instructions will work:
https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions.md

**Comment by pranavburnwal** [comment]
Thanks! Will try!

Will reopen if I get stuck.

**Comment by Suleman-Elahi** [comment]
Can't run...even java is up to date.
![image](https://user-images.githubusercontent.com/24384996/63165838-302ed800-c04a-11e9-92f5-16894ae03815.png)

**Comment by stefnotch** [comment]
`java -version` and post the output

**Comment by Suleman-Elahi** [comment]
```
C:\>java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**Comment by stefnotch** [comment]
That is rather strange. The first message basically says that you have Java 8 (class file version 52.0) and need Java 12 (class file version 56.0). However, it appears that you have Java 12 installed.
I suppose you could check if there is a stray Java 8 version still installed on your system.

**Comment by Suleman-Elahi** [comment]
I installed JDK from here after googling it by myself and it seems to be working fine.
https://jdk.java.net/13/

Thanks...

**Comment by MystesofEternity** [comment]
@Suleman-Elahi Can you post your PATH variables in here? Censor/Remove/Redact your Windows username if need be but we need to find out if you have some hideous path that points to a Java 8 so we can further diagnose this problem.
