### ISSUE TITLE
Severe aliasing in specific anime.

### ISSUE THREAD

**Issue by Artins90** [bloc97/Anime4K#60]
Hi,
I have switched over to MPV from my older madvr setup in order to use the latest version of Anime4k.
It's working fine for most anime but I came across this severe case of aliasing today:
Magia Record - Mahou Shoujo Madoka Magica Gaiden - 04 / 07:31
![Screenshot (10)](https://user-images.githubusercontent.com/28777957/73322907-ffcca600-4245-11ea-8736-973bdffff067.png)

Same scene with Madvr ngu standard:
![Screenshot (11)](https://user-images.githubusercontent.com/28777957/73323054-749fe000-4246-11ea-9860-a8e1e7fd6ff9.png)

I was wondering if there is something wrong with the way I set up mpv, I am going to attach the configuration file.
[mpv.zip](https://github.com/bloc97/Anime4K/files/4125901/mpv.zip)

Clip: http://www.mediafire.com/file/xbz14aq5t5u9pu7/a.mkv/file

**Comment by bloc97** [comment]
I see... There's ringing in the original video file, but there's something wrong with the v1.0 RC2 adaptive version. Usually the algorithm should not enhance ringing like this. I think for these kind of anime where the image is already pre-sharpened, we should release a even weaker version of Anime4K.

However, if you try the UltraFast version right now it does work better, since it is much weaker than the others (less risk of worsening the image, but less sharp). 

![](https://user-images.githubusercontent.com/567732/73393031-f7598700-42a8-11ea-84de-b0ed04836560.jpg)

Since the algorithm is extremely dumb and cannot take in account for every failure case, I will probably release the stable 1.0 soon with different strengths and implementations. I'll see what I can do.

**Comment by bloc97** [comment]
Fixed in latest version, v2.0 RC (Experimental).

![AnimeSharp2x](https://user-images.githubusercontent.com/567732/75601892-cded7000-5a8d-11ea-8ee5-e6d5dd3dab3f.jpg)
