### ISSUE TITLE
not working with .gif files

### ISSUE THREAD

**Issue by gin9980** [bloc97/Anime4K#91]
Using Anime4k shaders doesn't work with .gif files, it just shows a transparent background. Is this intended to not work with animated gifs?

**Comment by bloc97** [comment]
MPV does not process PNG and GIF files the same compared to AVC and JPEG files. Most Anime4K shaders work on the Luma channel, and PNG/GIF files do not have a Luma channel (they only have R/G/B).

**Comment by gin9980** [comment]
> 
> 
> MPV does not process PNG and GIF files the same compared to AVC and JPEG files. Most Anime4K shaders work on the Luma channel, and PNG/GIF files do not have a Luma channel (they only have R/G/B).

Is there a filter or settting that works for for images then? I'm not familiar with all the shaders avaible.

**Comment by gin9980** [comment]
Got it fixed.

**Comment by Rabcor** [comment]
> Got it fixed.

Mind sharing how you fixed it?

**Comment by gin9980** [comment]
> 
> 
> > Got it fixed.
> 
> Mind sharing how you fixed it?

convert to a video format like webm losslessly to make it work or don't use it at all and use the normal scalers with shaders like SSimDownscaler/SSimSuperRes instead of the anime4k shader. I think first choice is better.

**Comment by Rabcor** [comment]
@gin9980 wow that is so convoluted.

I was looking into this and found a different solution.

```
[extension.gif]
vf-append=format=yuv444p 									#Fix compatibility for Anime4K shaders.
[extension.png]
profile=extension.gif										#Fix compatibility for Anime4K shaders.
```

You may lose some color data in the conversion (personally I don't notice anything), but it enables gifs and pngs while anime4k is enabled.

Imo Anime4k is indispensible, it's such a good upscaler, and who says you can't just use both anime4k and SSim SuperRes (and SSim Downscaler too while at it)?

Whatever loss of color data there may be in the color format conversion, I feel that it is a worthwhile tradeoff for how much better fidelity you get in the end (especially since it's fairly common for gifs to be quite low-res and noisy, making the upscaling and denoising even more important than on regular videos)

**Comment by gin9980** [comment]
> 
> 
> @gin9980 wow that is so convoluted.
> 
> I was looking into this and found a different solution.
> 
> ```
> [extension.gif]
> vf-append=format=yuv444p 									#Fix compatibility for Anime4K shaders.
> [extension.png]
> profile=extension.gif										#Fix compatibility for Anime4K shaders.
> ```
> 
> You may lose some color data in the conversion (personally I don't notice anything), but it enables gifs and pngs while anime4k is enabled.
> 
> Imo Anime4k is indispensible, it's such a good upscaler, and who says you can't just use both anime4k and SSim SuperRes (and SSim Downscaler too while at it)?
> 
> Whatever loss of color data there may be in the color format conversion, I feel that it is a worthwhile tradeoff for how much better fidelity you get in the end (especially since it's fairly common for gifs to be quite low-res and noisy, making the upscaling and denoising even more important than on regular videos)

tried that before but the color shift, it was too much of a color change on my hardware color calibrated monitor, also used ICC profiles with MPV

**Comment by Rabcor** [comment]
Yeah I understand, sometimes the color accuracy is quite important, our use cases seem to be quite different perhaps as I don't need any such accuracy in my case, and it's a perfectly satisfying solution for me since on the handful of gifs I tested it there really wasn't any color difference I could notice (obviously there has to be some color difference, it's a lossy conversion after all, it probably introduces some banding as well, but not bad enough to bother me for my use case, I don't look at that many gifs and not that often either in the first place, and when I do it's nothing important. As for PNGs, I'm unlikely to ever actually view them in MPV :P )

**Comment by bloc97** [comment]
@Rabcor @gin9980 There shouldn't be any loss of color when converting from 256 bit indexed color for GIFs to YUV444. I think there is unnecessary color correction being applied somewhere.

**Comment by Rabcor** [comment]
> @Rabcor @gin9980 There shouldn't be any loss of color when converting from 256 bit indexed color for GIFs to YUV444. I think there is unnecessary color correction being applied somewhere.

Ah it's not so simple, not all gifs these days are 256 bit indexed colors. True color gifs have been around for a while now, and quite a lot of them are circulating.

And I did actually (100%) notice some banding introduced when using the color conversion hack that wasn't there when the gif was viewed normally (e.g. --no-config);

There's also the matter of PNGs which most certainly are almost always in true color.

I posted this issue earlier on mpv's github (i mistakenly thought that it was a problem with the vulkan and d3d11 renderers, but as it turns out actually, opengl was not applying the anime4k shader which was why I did not have this issue when using opengl; which is strange af, since it's a glsl shader so if it should work anywhere, it should work with opengl...)

Although that's all been sorted now, some guy suggested fixing this by inserting a pass that hooks RGB and saves LUMA should work (by allowing later passes tobind/reference LUMA).
