### ISSUE TITLE
21:9 support

### ISSUE THREAD

**Issue by xXHenlolXx** [bloc97/Anime4K#92]
I wanted to know if the shader provides support for non-linear upscale. 2560x1080 is 33% bigger than 1920x1080, and the "no-keepaspect" mpv's command allow to stretch the image. Thin and dark lines already provides a nice upgrade, but I was wondering about the upscale itself, as it is not activated automatically while playing a video.

Thanks in advance.

**Comment by bloc97** [comment]
In each shader stage there is this line of code:
`//!WHEN OUTPUT.w NATIVE.w / 1.200 > OUTPUT.h NATIVE.h / 1.200 > *`
If you remove them, the shader will always run.

I would suggest simply using notepad or any other text editor, and use the replace function to quickly remove all the lines.

**Comment by xXHenlolXx** [comment]
I tried with "Anime4K_Upscale_CNN_L_x2", but ended up with a green screen, doesn't matter if it was v0.31 or v0.32. Also, I was thinking, is it possible to use your shader on normal 1920x1080 displays to do supersampling? Even if the improvement is minimal, it would be usable for more people

**Comment by bloc97** [comment]
Are you sure the replacement was done correctly? I've tried on my end and it works. Note that there are multiple shader stages per file, and you have to remove all `!WHEN` expressions, not just the first one.

Here's the modified version I used:
[Anime4K_Upscale_CNN_L_x2_Ignore.zip](https://github.com/bloc97/Anime4K/files/4755105/Anime4K_Upscale_CNN_L_x2_Ignore.zip)

Also, since the pure upscale shaders are only doing an inverse of a downsampling function, they would have no effect if downsampled afterwards by supersampling. However, Upscale+Deblur and Upscale+Denoise will have noticeable effects, as they do more than just upscaling.

**Comment by xXHenlolXx** [comment]
Yeah, it was probably my fault, now it's working.

> Also, since the pure upscale shaders are only doing an inverse of a downsampling function, they would have no effect if downsampled afterwards by supersampling. However, Upscale+Deblur and Upscale+Denoise will have noticeable effects, as they do more than just upscaling.

I see
